theme: jekyll-theme-slate
show_downloads: true
github:
  repository_url: https://git.x4m3.rocks/vim-epitech
  zip_url: https://git.x4m3.rocks/vim-epitech/snapshot/vim-epitech-master.zip
  tar_url: https://git.x4m3.rocks/vim-epitech/snapshot/vim-epitech-master.tar.xz
